### ISSUE TITLE
code blocks with plantuml example renders as an img element

### ISSUE THREAD

**Issue by emmaindal** [mikitex70/plantuml-markdown#45] opened 2020-08-03 14:46 UTC
Hi,

I'm trying to include examples of plantuml syntax in code blocks and from version 3.1.3 and above this seems to be broken. Instead of render the example snippet it renders the generated img element. 

**V.3.1.2**
![Screen Shot 2020-08-03 at 3 20 55 PM](https://user-images.githubusercontent.com/25153114/89194916-4fe74500-d5a8-11ea-8c6e-49f9ed50cf92.png)

**V.3.3.0**
![Screen Shot 2020-08-03 at 3 34 10 PM](https://user-images.githubusercontent.com/25153114/89194927-537acc00-d5a8-11ea-9ebc-683d343cf36f.png)

The usage of code block snippet

![Screen Shot 2020-08-03 at 4 46 00 PM](https://user-images.githubusercontent.com/25153114/89195269-d4d25e80-d5a8-11ea-8ff8-df17e23e0078.png)

There may be another way to use plantuml examples in code blocks that I'm not aware of, feel free to point me in the right direction if so. 

Thanks!

**Comment by mikitex70** [comment] 2020-08-03 17:00
What tool are you using, `markdown_py`, `mkdocs`, or some other?
The `fenced_code` extension must be enabled (I suppose is already so) and you must change the plantuml plugin priority to be lower than 25 (the priority of `fenced_code`). For example, using the `markdown_py` create a `config.yml` with:
```yaml
plantuml_markdown:
  priority: 24
```

then use `markdown_py -x plantuml_markdown -c config.py infile.md > outfile.html`
For `mkdocs` the configuration goes in `mkdocs.yml`.
Maybe I can modify the default priority to be `20`, so this configuration will not be needed.
Let me know if this solves your issue.

**Comment by emmaindal** [comment] 2020-08-03 20:14
@mikitex70 Thanks for fast response. I'm using mkdocs.

I'll look more into it tomorrow but with this approach, the used syntax above, that actually should render a diagram will not work it seems like. Since the fenced code extension will always have higher priority and thereby render the plantuml snippet as a code block even though it should be rendered as a img. So yes, it will maybe solve the issue for the code block with the plantuml syntax example but it will also open up a new issue for one of the multiple syntax options that one can use. 

Would it instead be possible to add a rendering check to this extension that doesn't render the img if it's wrapped by a code block or something similar?

**Comment by mikitex70** [comment] 2020-08-05 05:59
Hi @emmaindal,
I can't detect if a diagram is wrapped inside another block because:
* I cannot insert into the plugin a detection for syntax of other plugins, what would happen if they change their syntax or i a new conflicting plugin would be created?
* `fenced_code` isn't the only plugin which can conflict with `plantuml_markdown`, see #38 which was resolved with the `priority` options

The correct way is to adjust the `priority` option to adapt processing to the used plugins, which is the method intoduced in `markdown_py` 3 to solve this kind of problems.
I can lower the default `priority` from `30` (actual value) to `20` in the next release, as it make sense that `fenced_block` needs to be always processed before `plantuml_markdown`.
In the meanwhile you can configure the `priority` option in the `mkdocs` plugin configuration using something like:

```yaml
plugins:
    - plantuml_markdown:
        priority: 20
```

**Comment by emmaindal** [comment] 2020-08-10 08:01
Hi @mikitex70 
Thanks for your response. I understand, make sense. 

I can confirm lower the priority works. But as mentioned above, this comes with a limitation (as far as I can see) of not being able to use one of the two syntax choices, the "GitLab/GitHub block syntax". This is the one I mainly use, so just need to switch out my diagrams to use the other one `::uml:: ::end-uml::`. Might be good to include in any release notes. 

I'll keep use the working version 3.1.2 until next release. Thank you!

**Comment by mikitex70** [comment] 2020-08-20 18:08
@emmaindal, can you give me a simple diagram example that isn't rendered correctly with the 3.3.0 release, even with lowered priority?
Lowering the priority should fix rendering with the "GitLab/GitHub block syntax"; if so I will decrease the `plantuml-markdown` plugin priority so it works out of the box without configurations.

**Comment by emmaindal** [comment] 2020-08-24 06:38
Hi @mikitex70 Thank you for fixing this issue and even with keeping the option of using the "GitLab/GitHub block syntax", we will give it a try to upgrade to the new version and let you know if we run in to any other issues.

**Comment by cmdkeen** [comment] 2020-10-27 13:43
This solution doesn't work if you have multiple fenced blocks on the page mixed in with uml blocks. The combination of _replace_block and the FENCED_CODE_RE regex means it will jump over any intermediate sections that match FENCED_BLOCK_RE.

Example:
![image](https://user-images.githubusercontent.com/54735/97309400-e2228080-1859-11eb-9669-798d6d5d2246.png)

The middle inline block doesn't get picked up for processing because of the second fenced block being found first.

![image](https://user-images.githubusercontent.com/54735/97309675-3f1e3680-185a-11eb-9944-77ca09b2e058.png)

(This is a bit of an edge case, I can work around, and generally this library has been brilliant - keep up the good work!)

**Closed** 2020-10-28 19:06 UTC
Labels: bug

**Comment by mikitex70** [comment] 2020-10-28 19:16
Thanks @cmdkeen for reporting the issue.
Now it should be fixed (at least it passes the test for this kind of error).
Try with a `pip install -U plantuml_markdown`, it should download the `3.4.1` version.

**Comment by cmdkeen** [comment] 2020-10-28 21:14
Thanks @mikitex70 for the quick turnaround - happy to confirm that I can no longer reproduce with 3.4.1

**Comment by mschoettle** [comment] 2023-02-14 20:52
I am using `plantuml-markdown` in combination with `mkdocs-material` and had to wrap it in a code block with six backticks:

<pre>
``````markdown
```plantuml
Alice -> Bob: Hi!
```
``````
</pre>

I saw that somewhere but don't remember where it was.

**Comment by mikitex70** [comment] 2023-02-15 06:48
Hi @mschoettle, you must activate the `fenced_code` plugin to be able to wrap code blocks.
From the command line use options like `-x fencde_code -x plantuml_markdown`, for mkdocs see the documentation.
It is not necessary to use 6 backticks, it is enough to use 4 (the number of backticks of the plantuml code block plus 1).

**Comment by mschoettle** [comment] 2023-02-15 21:04
`fenced_code` is already activated. You are correct, anything above 3 backticks works.
