### ISSUE TITLE
plugin does not work with markdown.extensions.fenced_code

### ISSUE THREAD

**Issue by ghost** [mikitex70/plantuml-markdown#8] opened 2018-02-05 08:07 UTC
fenced_code extension is removing gitlab block-style code markers before plantuml
is running.

**Comment by lu-zero** [comment] 2018-02-28 15:50
the current python markdown seems to do something even worse if codehilite is enabled

**Comment by mikitex70** [comment] 2018-03-01 12:36
The problem is in the `fenced_code` plugin, which parses text before every plugin.
In the `fenced_code plugin` there is cabled a workaround for the `codehilite plugin`; I'm trying to register the `plantuml` plugin before `fenced_code`, maybe with a _monkey patch_.

**Comment by lu-zero** [comment] 2018-03-01 13:10
Yes, my local solution had been patching fenced code and call it a day :)

**Comment by q3aiml** [comment] 2018-03-16 16:59
Here's how I fixed this: https://github.com/q3aiml/plantuml-markdown/commit/df3b0ada1c32aa92d1ae4668fae6bdd9b4c4456c. I haven't opened a PR because I only retained support for the github backtick style block syntax. The ::uml:: syntax could still work but the different opening and closing tags likely require a separate regex.

**Comment by mikitex70** [comment] 2018-03-18 15:24
Thanks @q3aiml, I will study your changes and try to merge them in the existing code.

**Comment by mikitex70** [comment] 2018-03-26 16:43
Hi @q3aiml, I've managed to merge your proprosed code.
I need to do other (small) changes (comment the code) but it should work.
I'm planning to write some test; in the meanwhile can you do some small run to see if all is working as expected?
Thanks again for you contribution.

**Comment by q3aiml** [comment] 2018-03-27 15:24
:+1: looks good here. Both styles are working. Thanks so much for reviewing and doing all the work to make it mergeable

**Comment by mikitex70** [comment] 2018-03-31 15:41
I'm working on, I'm writing some unit test to keep the code tested.
Be patient, I will try to fix it in this weekend.
What branch have you used, the `master` or the `develop` branch?

**Comment by q3aiml** [comment] 2018-03-31 17:02
@seanhoughton do you have a small example? I have only done basic testing but it works if I take the develop branch and drop the example from the readme in a doc twice. It was also working with my documents but they are admittedly all fairly similar. Or maybe it depends on either the markdown config or version?

**Comment by mikitex70** [comment] 2018-04-18 19:12
I've release the version v1.2.2 that should fix working with the fenced_code plugin.
I've also added some test, just to avoid regressions.

**Comment by mikitex70** [comment] 2018-04-19 18:48
Released version 1.2.3, which fixes an issue with Python 2.7.
Now the plugin is tested with various versions of Python, from 2.7 to 3.6.
I hope this will reduce the possibility of regressions.

**Closed** 2018-07-08 14:44 UTC
Labels: bug
